parent_menu: LevelEditor.MainMenu.my menu
items:
  - name: my menu
    items:
      - name: my item
        command: print("Hello World")
      - name: my sub menu
        items:
          - name: sub item 1
            command: print("Hello World")
          - name: sub item 2
            command: print("Hello World")
      - name: my item2
        command: import mytool; mytool.window.show()
