parent: LevelEditor.MainMenu.Custom Menu  # set parent to the menu from the previous example
items:
  - label: Custom Menu  # this is now a submenu instead of a top level menu
    items:
      - label: Test
        command: print("Test")
